#!/bin/bash 

java -cp /opt/sfw/generic/jmlunitng-1.4/lib/jmlunitng.jar:/home/sv/openjml-4.2.2/plugins/org.jmlspecs.OpenJMLUI_0.5.33/jmlruntime.jar:testbin com.beust.testng.TestNG test_movePlayer.xml
