/*
 * Test data strategy for Position.
 *
 * Generated by JMLUnitNG 1.4 (116/OpenJML-20131218-REV3178), 2014-10-28 13:53 +0100.
 * (do not modify this comment, it is used by JMLUnitNG clean-up routines)
 */

import java.util.LinkedList;
import java.util.List;

import org.jmlspecs.jmlunitng.iterator.InstantiationIterator;
import org.jmlspecs.jmlunitng.iterator.IteratorAdapter;
import org.jmlspecs.jmlunitng.iterator.NonNullMultiIterator;
import org.jmlspecs.jmlunitng.iterator.ObjectArrayIterator;
import org.jmlspecs.jmlunitng.iterator.RepeatedAccessIterator;
import org.jmlspecs.jmlunitng.strategy.ObjectStrategy;

/**
 * Test data strategy for Position. Provides
 * instances of Position for testing, using
 * parameters from constructor tests.
 * 
 * @author JMLUnitNG 1.4 (116/OpenJML-20131218-REV3178)
 * @version 2014-10-28 13:53 +0100
 */
public /*@ nullable_by_default */ class Position_InstanceStrategy extends ObjectStrategy {
  /**
   * @return local-scope instances of Position.
   */
  public RepeatedAccessIterator<?> localValues() {
    return new ObjectArrayIterator<Object>
    (new Object[]
     { /* add Position values or generators here */ });
  }

  /**
   * @return default instances of Position, generated
   *  using constructor test parameters.
   */ 
  public RepeatedAccessIterator<Position> defaultValues() {
    final List<RepeatedAccessIterator<Position>> iters = 
      new LinkedList<RepeatedAccessIterator<Position>>();

    // an instantiation iterator for the default constructor
    // (if there isn't one, it will fail silently)
    iters.add(new InstantiationIterator<Position>
      (Position.class, 
       new Class<?>[0], 
       new ObjectArrayIterator<Object[]>(new Object[][]{{}})));

    // parameters for method Position(int, int)
    iters.add(new InstantiationIterator<Position>
      (Position.class, 
       new Class<?>[]
       {int.class, 
        int.class},
       Position_JML_Test.p_Position__int_x__int_y__0().wrapped()));

    return new NonNullMultiIterator<Position>(iters);
  }

  /**
   * Constructor. The boolean parameter to <code>setReflective</code>
   * determines whether or not reflection will be used to generate
   * test objects, and the int parameter to <code>setMaxRecursionDepth</code>
   * determines how many levels reflective generation of self-referential classes
   * will recurse.
   *
   * @see ObjectStrategy#setReflective(boolean)
   * @see ObjectStrategy#setMaxRecursionDepth(int)
   */
  public Position_InstanceStrategy() {
    super(Position.class);
    setReflective(true);
    // uncomment to control the maximum reflective instantiation
    // recursion depth, 0 by default
    // setMaxRecursionDepth(0);
  }
}
