/*
 * Test data strategy for Game.
 *
 * Generated by JMLUnitNG 1.4 (116/OpenJML-20131218-REV3178), 2014-10-28 13:23 +0100.
 * (do not modify this comment, it is used by JMLUnitNG clean-up routines)
 */

import org.jmlspecs.jmlunitng.iterator.ObjectArrayIterator;
import org.jmlspecs.jmlunitng.iterator.RepeatedAccessIterator;

/**
 * Test data strategy for Game. Provides
 * test values for parameter "Position newPosition" 
 * of method "boolean movePlayer(Position)". 
 * 
 * @author JMLUnitNG 1.4 (116/OpenJML-20131218-REV3178)
 * @version 2014-10-28 13:23 +0100
 */
public /*@ nullable_by_default */ class Game_movePlayer__Position_newPosition__0__newPosition

  

  extends Game_ClassStrategy_Position {
  /**
   * @return local-scope values for parameter 
   *  "Position newPosition".
   */
   
  public Position genPos (int x, int y) {
    return new Position (x,y);
  }

  public RepeatedAccessIterator<?> localValues() {
    return new ObjectArrayIterator<Object>
    (new Object[]
     { genPos(3,3), genPos(3,4), genPos(3,5), genPos(4,3), genPos(4,5), genPos(5,3), genPos(5,4), genPos(5,5), genPos(6,6), genPos(2,2) });
  }   
   

  /**
   * Constructor.
   * The use of reflection can be controlled here for  
   * "Position newPosition" of method "boolean movePlayer(Position)" 
   * by changing the parameters to <code>setReflective</code>
   * and <code>setMaxRecursionDepth<code>.
   * In addition, the data generators used can be changed by adding 
   * additional data class lines, or by removing some of the automatically 
   * generated ones. Since this is the lowest level of strategy, the 
   * behavior will be exactly as you specify here if you clear the existing 
   * list of classes first.
   *
   * @see NonPrimitiveStrategy#addDataClass(Class<?>)
   * @see NonPrimitiveStrategy#clearDataClasses()
   * @see ObjectStrategy#setReflective(boolean)
   * @see ObjectStrategy#setMaxRecursionDepth(int)
   */
  public Game_movePlayer__Position_newPosition__0__newPosition() {
    super();
    // uncomment to control the maximum reflective instantiation
    // recursion depth, 0 by default
    // setMaxRecursionDepth(0);
  }
}
